### ISSUE TITLE
Bulk documents API fxns

### ISSUE THREAD

**Issue by sckott** [ropensci/sofa#19]
http://wiki.apache.org/couchdb/HTTP_Bulk_Document_API

**Comment by andrewcstewart** [comment]
For this item, are you thinking something along the lines of creating/updating a bulk of docs from a data.frame?  I need to code this up myself, so I could put it in a pull request if you want to include it.

**Comment by sckott** [comment]
@andrewcstewart i wasn't specifically thinking of going directly from a data.frame, but simply supporting the bulk_docs endpoint, for both read and write of json string or list objects 

do go from data.frame's that seems like a separate issue - and we could have helper fxns for going from a data.frame directly to inserting documents into couchdb without having to do the intermediate step of converting to json string or list, see #27

**Comment by sckott** [comment]
still need to implement methods for 

- [ ] list
- [ ] character (json string that is)

**Comment by sckott** [comment]
list method isn't fully working yet

**Comment by sckott** [comment]
seems to work okay, will open up new issues if not working
