### ISSUE TITLE
Improve the readme with more examples

### ISSUE THREAD

**Issue by sckott** [ropensci/sofa#23]

**Comment by michellymenezes** [comment]
Hi, I'd like to help. What kind of new examples do you want?

**Comment by sckott** [comment]
👋 @michellymenezes It'd be good to add more info in general to the README about CouchDB and this pkg. For examples, I don't think we want examples for every single function/etc., but covering a few of them, and perhaps a very  brief example of using many functions together to achieve some task 

let me know if you have any questions!
