### ISSUE TITLE
Question on how get_view works

### ISSUE THREAD

**Issue by andrewcstewart** [ropensci/sofa#28]
I'm somewhat confused by the function definition for get_view().

```
view_get(cushion = "localhost", dbname, design_name, as = "json", ...)
```

It looks like in your examples that you're passing the name of the view to the design_name parameter, but shouldn't there be separate design_name and view_name parameters?

**Comment by sckott** [comment]
sorry, i haven't worked much on those fxns, so they may not work that well. i'll take a look...

**Comment by sckott** [comment]
@andrewcstewart sorry for long delay on this, finally getting this in shape for CRAN and in tune with Couchdb v2. 

try again after reinstalling `devtools::install_github("ropensci/sofa")` 

renamed functions to be prefixed with `design_*()`

**Comment by sckott** [comment]
there is now a sep. design param and view name param
