### ISSUE TITLE
A number of routes don't seem to work in CouchDB v2

### ISSUE THREAD

**Issue by sckott** [ropensci/sofa#44]
* `_stats` (removed from couch, so remove from sofa)
* `_log` (removed from couch, didn't have a fxn in sofa anyway)
* `_config` (removed from couch, didn't have a fxn in sofa anyway)
* ~~`_active_tasks`~~ (nevermind, does work)
* ~~`_session`~~ (nevermind, does work)

and probably more 

Whereas in Couchdb v1.6, all these work fine

anyone have ideas? Is it possible i installed v2 wrong?  I installed the app from http://couchdb.apache.org/#download and start it from `/Applications`

**Comment by sckott** [comment]
@patperu @katsel  maybe you know what I'm doing wrong here?

**Comment by patperu** [comment]
Hi @sckott 
I'm afraid that I can't help you here :disappointed: One thing I remember is that v2 doesn’t create system databases, see http://docs.couchdb.org/en/2.0.0/install/index.html#single-node-setup
Maybe @klaemo can help
Ciao Patrick

**Comment by katsel** [comment]
`active_tasks` and `_session` are working for me on 2.0.

The `_stats`, `_log` and `_config` may have been removed due to interfering with cluster functionality, see e.g. https://github.com/apache/couchdb-fauxton/pull/153 and linked mailing list discussion.

**Comment by sckott** [comment]
thanks very much both. 

@katsel indeed, i was mistaken,`_active_tasks` and `_session` do work, woopsy. 

Okay, `_stats` is gone, got it. 

I didn't see specific mention of  `_log` and `_config` being removed in that PR I don't think, but I'll assume they have been removed as well

**Comment by sckott** [comment]
all sorted
