### ISSUE TITLE
Error: (400) - Referer header required

### ISSUE THREAD

**Issue by wmatwijec** [ropensci/sofa#48]
Getting this with 1.6.1.

query all in one json blob

```
> db_explain(z, dbname = "omdb", query = '{
+            "selector": {
+            "_id": {
+            "$gt": null
+            }
+            }
+            }')
Error: (400) - Referer header required.
 ```

**Comment by sckott** [comment]
thanks for the issue. `sofa` was built targeting Couch v2 and greater, so I haven't been checking if <v2 will work in general

specifically for this, the query interface only exists in v2 and greater. you can see the docs page for this feature does not exist in 1.6.1 http://docs.couchdb.org/en/1.6.1/api/database/find.html
