### ISSUE TITLE
view_search

### ISSUE THREAD

**Issue by wmatwijec** [ropensci/sofa#49]
Thanks once again for this package.  I have moved from 1.6.1 Now getting this error.

> res <- view_search(x, dbname='omdb', design='view2')
Error: could not find function "view_search"

**Comment by sckott** [comment]
see the vignette https://cran.rstudio.com/web/packages/sofa/vignettes/sofa_vignette.html 

see the fxns prefixed with `design_`

**Comment by sckott** [comment]
closing due to inactvity
