### ISSUE TITLE
Change `view_search` to `design_search` in the examples

### ISSUE THREAD

**Issue by patperu** [ropensci/sofa#55]
Change `view_search` to `design_search` in the examples 
https://github.com/ropensci/sofa/blob/master/R/design.R#L62-L24

**Comment by michellymenezes** [comment]
Hi, I've made this change for you.

**Comment by patperu** [comment]
Hi @michellymenezes
thank you very much! I totally forgot this issue... Currently I'm offline and can't merge your PR, but maybe @sckott can do it. Otherwise I'll do it on Friday.


Am 16. Oktober 2017 05:08:28 MESZ schrieb Michelly Menezes <notifications@github.com>:
>Hi, I've made this change for you.

**Comment by sckott** [comment]
fixed in #57
