### ISSUE TITLE
design_search needs POST support to use key feature

### ISSUE THREAD

**Issue by davbwhit** [ropensci/sofa#56]
Get "Error: (400) - invalid UTF-8 JSON" when trying to specify a key to retrieve from a view.

Couch documentation 10.5.4 indicates:
Unlike GET /{db}/_design/{ddoc}/_view/{view} for accessing views, the POST method supports the specification of explicit keys to be retrieved from the view results.  The remainder of the POST view functionality is identical to the GET /{db}/_design/{ddoc}/_view/{view} API.

Any chance of getting an updated design_search with POST support to handle the super-set of features?

**Comment by sckott** [comment]
hi @davbwhit thanks for opening the issue

I'll have a look, perhaps may be a quick fix

**Comment by sckott** [comment]
@davbwhit can you try again after reinstalling like `devtools::install_github("ropensci/sofa")`

can do POST now if you use `body` parameter, and also `design_search_many` function added for sending many queries at once.

**Comment by tumulurig3** [comment]
How do you specify a key? I have a composite key on two fields , on is a id field (string) and other is a timstamp that is an integer. Trying variations of the following and getting various errors.

```
design_search(connection, 'bydb', 'designname', 'viewname', key = list('09f3eef7b47164b0ed9f1b7775f3e5be', 1511170394))
Error in lapply(x, f) : attempt to apply non-function
```

**Comment by sckott** [comment]
@tumulurig3 try giving that list to the `body` parameter, like `body = list(keys = c('09f3eef7b47164b0ed9f1b7775f3e5be', 1511170394))`

**Comment by tumulurig3** [comment]
Had some issue making the above work, but re-starting RStudio and re-invoking the library made the call work with above format. However, it returns no documents, even though I know that key exists in the DB. Perhaps some other issue. Thank you!
