### ISSUE TITLE
db_alldocs is severely limited in R sofa pacakge due to use of character vector size limited to 2^31-1 length

### ISSUE THREAD

**Issue by tumulurig3** [ropensci/sofa#64]
I have a fairly small Cloudant collection with about 2.6 million documents. I am trying to pull all of them into memory to work with the full data set. This just won't work in R.

Currently, my workaround is to pull it all using Python, dump to a JSON text file, read in R using `readLines` and do `lapply` to convert to list using `fromJSON`. While this works, it is kind of annoying to switch between environments, store data into intermediate files and such.

```
df <- db_alldocs(myCuishion, 'my-db-collection', include_docs = TRUE)
Error in readBin(self$content, character()) : 
  R character strings are limited to 2^31-1 bytes
```

Is there any possible way to address this limitation?

**Comment by sckott** [comment]
i'll have a look

**Comment by sckott** [comment]
adding ability to write to disk instead of saving within R session

**Comment by sckott** [comment]
@tumulurig3 try again after reinstalling `devtools::install_github("ropensci/sofa")` - see `disk` parameter in `db_alldocs` and see the new example added for how to use. 

does that solve your problem?
