### ISSUE TITLE
New Maintainer Wanted :-)

### ISSUE THREAD

**Issue by maelle** [ropensci/sofa#81]
(or new maintainer _team_)

This package was archived on GitHub but not on CRAN.
If someone has interest in maintaining it, it won't be archived on CRAN.
We'd transfer it back to the ropensci GitHub organization.

If you're interested, please comment in the issue.
For more info, see
- [our guidance on Changing package maintainers](https://devguide.ropensci.org/changing-maintainers.html);
- [our Package Curation Policy](https://devguide.ropensci.org/curationpolicy.html);
- [Package Maintainer Cheatsheet](https://devdevguide.netlify.app/maintenance_cheatsheet.html);
- the blog post [What does it mean to maintain a package?](https://ropensci.org/blog/2023/02/07/what-does-it-mean-to-maintain-a-package/).

@ropensci-archive/admin

**Comment by eduardszoecs** [comment]
I would be interested to keep this on CRAN and therefore could offer maintenance (but with limited time).

**Comment by maelle** [comment]
Awesome, thank you @eduardszoecs! :pray:  I was about to put the call in tomorrow's monthly newsletter, is that fine with you if we wait to see if others volunteer between tomorrow and Friday next week? (I doubt there's anyone with unlimited time out there :grin:, nor does this package demand unlimited time, but maybe there could be a team so as not to overburden you?)

**Comment by maelle** [comment]
@eduardszoecs Sadly no one else volunteered, although that might still happen later! I've given you admin access to the repo.

Please update DESCRIPTION (@sckott will need to ok by email your next submission to CRAN, to validate the maintainer change)

We have a maintainer cheatsheet now: https://devdevguide.netlify.app/maintenance_cheatsheet.html

Thanks a ton for volunteering!!

**Comment by eduardszoecs** [comment]
@sckott 

I noticed there is a cloudant instance running? https://github.com/ropensci/sofa/blob/2c6a8aa0240e0566062af923d841ddd57ea0b96c/R/cushion.R#L65

Can you provide me the credentials or add them to the secret of the repo? Could us this for continuous testing...

**Comment by eduardszoecs** [comment]
@maelle How is the machinery behind https://docs.ropensci.org/sofa/?
I see its updated, but how does it work? I haven't seen any github action, or are you regulary checking out the repo and build that from there?

Just that I know how I could add / modify the docu there...

**Comment by maelle** [comment]
:wave: @eduardszoecs!

It's built on R-universe see https://ropensci.org/blog/2021/09/03/runiverse-docs/ and https://ropensci.r-universe.dev/builds

Each of the commit to the default branch in this repo has a pkgdown docs status see below 

![image](https://user-images.githubusercontent.com/8360597/232386270-52771e13-a8f9-4cbb-b230-8bc077785fd7.png)

**Comment by maelle** [comment]
Closing this but feel free to ask questions here or elsewhere @eduardszoecs! Thanks again!!
