### ISSUE TITLE
New Maintainer Wanted :-)

### ISSUE THREAD

**Issue by maelle** [ropensci/sofa#82]
(or new maintainer _team_)

If you're interested, please comment in the issue or email `info@ropensci.org`.

For more info, see
- [our guidance on Changing package maintainers](https://devguide.ropensci.org/changing-maintainers.html);
- [our Package Curation Policy](https://devguide.ropensci.org/curationpolicy.html);
- [Package Maintainer Cheatsheet](https://devdevguide.netlify.app/maintenance_cheatsheet.html);
- the blog post [What does it mean to maintain a package?](https://ropensci.org/blog/2023/02/07/what-does-it-mean-to-maintain-a-package/).

@ropensci/admin @eduardszoecs

**Comment by maelle** [comment]
Oops, re-opening until the DESCRIPTION file is updated.

**Comment by maelle** [comment]
@YaoxiangLi please keep the former maintainer listed in DESCRIPTION, but as "aut", not "cre" as the package can have only one "cre".

**Comment by YaoxiangLi** [comment]
Thanks Maëlle, updated as suggested, and I will close this issue.

**Comment by maelle** [comment]
Thank you!!
